#include<cstdio>
#include<cstdlib>
#include "Sudoku.h"
using namespace std;

void Sudoku::giveQuestion()
{
printf("8 0 0 0 0 0 0 0 0\n0 0 3 6 0 0 0 0 0\n0 7 0 0 9 0 2 0 0\n0 5 0 0 0 7 0 0 0\n0 0 0 0 4 5 7 0 0\n0 0 0 1 0 0 0 3 0\n0 0 1 0 0 0 0 6 8\n0 0 8 5 0 0 0 1 0\n0 9 0 0 0 0 4 0 0\n");
}
void Sudoku::readIn()
{
	int i,j;
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			scanf("%d",&thesudoku[i][j]);
		}
	}
}
void Sudoku::thebreak(int a)
{
	int i,j,bre=0,k;
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			 answer[a][i][j]=thesudokusol[i][j];
		}
	}
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			for(k=0;k<9;++k){
				thesudokuless[a][i][j][k]=0;
			}
		}
	}
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			if(thesudokusol[i][j]==0){
				for(k=0;;k++){
					if(thesudokurest[i][j][k]==0){break;}
					else{
						thesudokuless[a][i][j][k]=thesudokurest[i][j][k];
					}
				}
			}
		}
	}
	answer[a][I][J]=a;
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			if(answer[a][i][j]==0){
				  for(k=0;;++k){
					  if(thesudokuless[a][i][j][k]==0){break;}
					  else{
						    findanswer(a,i,j,thesudokuless[a][i][j][k]);
					  }
				  }
				  bre=1;
				  break;
			}
		}
		if(bre==1)break;
	}
}
void Sudoku::findanswer(int a,int x,int y,int fitin)
{
	int i,j,lin,str,alr=0,blos,blol;
	for(lin=0;lin<9;++lin){
		if(answer[a][x][lin]==fitin){
			alr=1;
		}
	}
	for(str=0;str<9;++str){
		if(answer[a][str][y]==fitin){
			alr=1;
		}
	}
	if(x>=0&&x<=2){
		if(y>=0&&y<=2){
                        for(blos=0;blos<3;++blos){
				for(blol=0;blol<3;++blol){
					 if(answer[a][blos][blol]==fitin){
						alr=1;
					}
				}
			}
		}
		if(y>=3&&y<=5){
			for(blos=0;blos<3;++blos){
				for(blol=3;blol<6;++blol){
					if(answer[a][blos][blol]==fitin){
						alr=1;
					}
				}
			}
		}
		if(y>=6&&y<=8){
			for(blos=0;blos<3;++blos){
				for(blol=6;blol<9;++blol){
					if(answer[a][blos][blol]==fitin){
						alr=1;
					}
				}
			}
		}
	}
	if(x>=3&&x<=5){
		if(y<=0&&y>=2){
                        for(blos=3;blos<6;++blos){
				for(blol=0;blol<3;++blol){
					 if(answer[a][blos][blol]==fitin){
						alr=1;
					}
				}
			}
		}
		if(y<=3&&y>=5){
			for(blos=3;blos<6;++blos){
				for(blol=3;blol<6;++blol){
					if(answer[a][blos][blol]==fitin){
						alr=1;
					}
				}
			}
		}
		if(y<=6&&y>=8){
			for(blos=3;blos<6;++blos){
				for(blol=6;blol<9;++blol){
					if(answer[a][blos][blol]==fitin){
						alr=1;
					}
				}
			}
		}
	}
	if(x>=6&&x<=8){
		if(y<=0&&y>=2){
                        for(blos=6;blos<9;++blos){
				for(blol=0;blol<3;++blol){
					 if(answer[a][blos][blol]==fitin){
						alr=1;
					}
				}
			}
		}
		if(y<=3&&y>=5){
			for(blos=6;blos<9;++blos){
				for(blol=3;blol<6;++blol){
					if(answer[a][blos][blol]==fitin){
						alr=1;
					}
				}
			}
		}
		if(y<=6&&y>=8){
			for(blos=6;blos<9;++blos){
				for(blol=6;blol<9;++blol){
					if(answer[a][blos][blol]==fitin){
						alr=1;
					}
				}
			}
		}
	}
	int nextone=0,k,A,B;
	if(alr==0){
		answer[a][x][y]=fitin;
		for(i=0;i<9;++i){
			for(j=0;j<9;++j){
				if(answer[a][i][j]==0){
					nextone=1;
					break;
				}
			}
			if(nextone==1)break;
		}
		if(nextone==0){
			++solveway;
			for(A=0;A<9;++A){
				for(B=0;B<9;++B){
					thetrueanswer[A][B]=answer[a][A][B];
				}
			}
		}
		else{
			for(k=0;;++k){
				if(thesudokuless[a][i][j][k]==0){break;}
				else{
					findanswer(a,i,j,thesudokuless[a][i][j][k]);
				}
			}
		}
	}
	answer[a][x][y]=0;
}
void Sudoku::judge()
{
	int i,j,lin,str,blol,blos;
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			if(thesudoku[i][j]!=0){
				for(lin=j+1;lin<9;++lin){
					if(thesudoku[i][j]==thesudoku[i][lin]){
						nop=nop+1;
						break;
					}
				}
				
				if(nop!=0)break;
				for(str=i+1;str<9;++str){
					if(thesudoku[i][j]==thesudoku[str][j]){
						nop=nop+1;
						break;
					}
				}
				if(nop!=0)break;
				if(i>=0&&i<=2){
					if(j>=0&&j<=2){
						for(blos=i;blos<3;++blos){
							for(blol=0;blol<3;++blol){
								if(thesudoku[i][j]==thesudoku[blos][blol]&&i!=blos&&j!=blol){
									nop=nop+1;
									break;
								}
							}
						}
					}
					if(j>=3&&j<=5){
                        	                for(blos=i;blos<3;++blos){
                                	                for(blol=3;blol<6;++blol){
                       		                                if(thesudoku[i][j]==thesudoku[blos][blol]&&i!=blos&&j!=blol){
                                                                	nop=nop+1;
                                                                	break;
                                                        	}
                                                	}
                                        	}
					}
					if(j>=6&&j<=8){
                                	        for(blos=i;blos<3;++blos){
                                                	for(blol=6;blol<9;++blol){
                                                        	if(thesudoku[i][j]==thesudoku[blos][blol]&&i!=blos&&j!=blol){
                                                                	nop=nop+1;
                                                                	break;
                                                       		}
                                                	}
                                        	}
					}
				}
                        	if(i>=3&&i<=5){
                                	if(j>=0&&j<=2){
                                        	for(blos=i;blos<6;++blos){
                                                	for(blol=0;blol<3;++blol){
                                                        	if(thesudoku[i][j]==thesudoku[blos][blol]&&i!=blos&&j!=blol){
                                                                	nop=nop+1;
                                                                	break;
                                                        	}
                                                	}
                                        	}
                                	}
                                	if(j>=3&&j<=5){
                                        	for(blos=i;blos<6;++blos){
                                                	for(blol=3;blol<6;++blol){
                                                        	if(thesudoku[i][j]==thesudoku[blos][blol]&&i!=blos&&j!=blol){
                                                                	nop=nop+1;
                                                                	break;
                                                        	}
                                                	}
                                        	}
                                	}
                                	if(j>=6&&j<=8){
                                        	for(blos=i;blos<6;++blos){
                                                	for(blol=6;blol<9;++blol){
                                                        	if(thesudoku[i][j]==thesudoku[blos][blol]&&i!=blos&&j!=blol){
                                                                	nop=nop+1;
                                                                	break;
                                                        	}
                                                	}
                                        	}
                                	}
                        	}
                        	if(i>=6&&i<=8){
                                	if(j>=0&&j<=2){
                                        	for(blos=i;blos<9;++blos){
                                                	for(blol=0;blol<3;++blol){
                                                        	if(thesudoku[i][j]==thesudoku[blos][blol]&&i!=blos&&j!=blol){
                                                                	nop=nop+1;
                                                                	break;
                                                        	}
                                                	}
                                        	}
                                	}
                                	if(j>=3&&j<=5){
                                        	for(blos=i;blos<9;++blos){
                                                	for(blol=3;blol<6;++blol){
                                                        	if(thesudoku[i][j]==thesudoku[blos][blol]&&i!=blos&&j!=blol){
                                                                	nop=nop+1;
                                                                	break;
                                                        	}
                                                	}
                                        	}
                                	}
                                	if(j>=6&&j<=8){
                                        	for(blos=i;blos<9;++blos){
                                                	for(blol=6;blol<9;++blol){
                                                        	if(thesudoku[i][j]==thesudoku[blos][blol]&&i!=blos&&j!=blol){
                                                                	nop=nop+1;
                                                                	break;
                                                        	}
                                                	}
                                        	}
                                	}
                        	}
			}
		}
		if(nop==1){
			printf("0");
			break;
		}
	}
}
void Sudoku::solve()
{
	int num[9],i,j,k,l,sol,lin,str,blol,blos,les,theans=0;
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			thesudokusol[i][j]=thesudoku[i][j];
		}
	}
	nop=0;
	judge();
	if(nop==1)exit(0);
	if(nop==0){
		for(;;){
		sol=0;
		for(i=0;i<9;++i){
			for(j=0;j<9;++j){
				if(thesudokusol[i][j]==0){
					for(k=0;k<9;++k){
						num[k]=k+1;
					}
					les=9;
					for(lin=0;lin<9;++lin){
						if(thesudokusol[i][lin]!=0&&num[thesudokusol[i][lin]-1]!=0){
							num[thesudokusol[i][lin]-1]=0;
							les=les-1;
						}
					}
					for(str=0;str<9;++str){
						if(thesudokusol[str][j]!=0&&num[thesudokusol[str][j]-1]!=0){
							num[thesudokusol[str][j]-1]=0;
							les=les-1;
						}
					}
					if(i>=0&&i<=2){
						if(j>=0&&j<=2){
		                                        for(blos=0;blos<3;++blos){
                		                                for(blol=0;blol<3;++blol){
                                		                        if(thesudokusol[blos][blol]!=0&&num[thesudokusol[blos][blol]-1]!=0){
                                                		                num[thesudokusol[blos][blol]-1]=0;
                                                                		les=les-1;
                                                        		}
                                                		}
                                        		}
						}
						if(j>=3&&j<=5){
	                               		        for(blos=0;blos<3;++blos){
                                                                for(blol=3;blol<6;++blol){
                                                                        if(thesudokusol[blos][blol]!=0&&num[thesudokusol[blos][blol]-1]!=0){
                                                                                num[thesudokusol[blos][blol]-1]=0;
                                                                                les=les-1;
                                                                        }
                                                                }
                                                        }
						}
						if(j>=6&&j<=8){
                                                        for(blos=0;blos<3;++blos){
                                                                for(blol=6;blol<9;++blol){
                                                                        if(thesudokusol[blos][blol]!=0&&num[thesudokusol[blos][blol]-1]!=0){
                                                                                num[thesudokusol[blos][blol]-1]=0;
                                                                                les=les-1;
                                                                        }
                                                                }
                                                        }
						}
					}
                                        if(i>=3&&i<=5){
                                                if(j>=0&&j<=2){
                                                        for(blos=3;blos<6;++blos){
                                                                for(blol=0;blol<3;++blol){
                                                                        if(thesudokusol[blos][blol]!=0&&num[thesudokusol[blos][blol]-1]!=0){
                                                                                num[thesudokusol[blos][blol]-1]=0;
                                                                                les=les-1;
                                                                        }
                                                                }
                                                        }
                                                }
                                                if(j>=3&&j<=5){
                                                        for(blos=3;blos<6;++blos){
                                                                for(blol=3;blol<6;++blol){
                                                                        if(thesudokusol[blos][blol]!=0&&num[thesudokusol[blos][blol]-1]!=0){
                                                                                num[thesudokusol[blos][blol]-1]=0;
                                                                                les=les-1;
                                                                        }
                                                                }
                                                        }
                                                }
                                                if(j>=6&&j<=8){
                                                        for(blos=3;blos<6;++blos){
                                                                for(blol=6;blol<9;++blol){
                                                                        if(thesudokusol[blos][blol]!=0&&num[thesudokusol[blos][blol]-1]!=0){
                                                                                num[thesudokusol[blos][blol]-1]=0;
                                                                                les=les-1;
                                                                        }
                                                                }
                                                        }
                                                }
                                        }
                                        if(i>=6&&i<=8){
                                                if(j>=0&&j<=2){
                                                        for(blos=6;blos<9;++blos){
                                                                for(blol=0;blol<3;++blol){
                                                                        if(thesudokusol[blos][blol]!=0&&num[thesudokusol[blos][blol]-1]!=0){
                                                                                num[thesudokusol[blos][blol]-1]=0;
                                                                                les=les-1;
                                                                        }
                                                                }
                                                        }
                                                }
                                                if(j>=3&&j<=5){
                                                        for(blos=6;blos<9;++blos){
                                                                for(blol=3;blol<6;++blol){
                                                                        if(thesudokusol[blos][blol]!=0&&num[thesudokusol[blos][blol]-1]!=0){
                                                                                num[thesudokusol[blos][blol]-1]=0;
                                                                                les=les-1;
                                                                        }
                                                                }
                                                        }
                                                }
                                                if(j>=6&&j<=8){
                                                        for(blos=6;blos<9;++blos){
                                                                for(blol=6;blol<9;++blol){
                                                                        if(thesudokusol[blos][blol]!=0&&num[thesudokusol[blos][blol]-1]!=0){
                                                                                num[thesudokusol[blos][blol]-1]=0;
                                                                                les=les-1;
                                                                        }
                                                                }
                                                        }
                                                }
                                        }
					if(les==1){
						for(k=0;k<9;++k){
							if(num[k]!=0){
								thesudokusol[i][j]=num[k];
								break;
							}
						}
						sol=1;
					}
					if(les==0){
						printf("0");
						exit(0);
					}
				}
			}
		}
		if(sol==0)break;
	}
	}
	for(I=0;I<9;++I){
		for(J=0;J<9;++J){
			if(thesudokusol[I][J]==0)theans=1;
			if(theans==1)break;
		}
		if(theans==1)break;
	}
	if(theans==0){
		printf("1\n");
		for(i=0;i<9;++i){
			for(j=0;j<9;++j){
				printf("%d%c",thesudokusol[i][j],j==8?'\n':' ');
			}
		}
	}
	else{
		for(i=0;i<9;++i){
			num[i]=i+1;
		}
		for(lin=0;lin<9;++lin){
			if(thesudokusol[I][lin]!=0){
				num[thesudokusol[I][lin]-1]=0;
			}
		}
		for(str=0;str<9;++str){
			if(thesudokusol[str][J]!=0){
				num[thesudokusol[str][J]-1]=0;
			}
		}
		if(I>=0&&I<=2){
			if(J>=0&&J<=2){
                                for(blos=0;blos<3;++blos){
					for(blol=0;blol<3;++blol){
                                                 if(thesudokusol[blos][blol]!=0){
							 num[thesudokusol[blos][blol]-1]=0;
						}
					}
				}
			}
			if(J>=3&&J<=5){
				for(blos=0;blos<3;++blos){
					for(blol=3;blol<6;++blol){
						if(thesudokusol[blos][blol]!=0){
							num[thesudokusol[blos][blol]-1]=0;
						}
					}
				}
			}
			if(J>=6&&J<=8){
				for(blos=0;blos<3;++blos){
					for(blol=6;blol<9;++blol){
						if(thesudokusol[blos][blol]!=0){
							num[thesudokusol[blos][blol]-1]=0;
						}
					}
				}
			}
		}
		if(I>=3&&I<=5){
			if(J>=0&&J<=2){
                                for(blos=3;blos<6;++blos){
					for(blol=0;blol<3;++blol){
                                                 if(thesudokusol[blos][blol]!=0){
							 num[thesudokusol[blos][blol]-1]=0;
						}
					}
				}
			}
			if(J>=3&&J<=5){
				for(blos=3;blos<6;++blos){
					for(blol=3;blol<6;++blol){
						if(thesudokusol[blos][blol]!=0){
							num[thesudokusol[blos][blol]-1]=0;
						}
					}
				}
			}
			if(J>=6&&J<=8){
				for(blos=3;blos<6;++blos){
					for(blol=6;blol<9;++blol){
						if(thesudokusol[blos][blol]!=0){
							num[thesudokusol[blos][blol]-1]=0;
						}
					}
				}
			}
		}
		if(I>=6&&I<=8){
			if(J>=0&&J<=2){
                                for(blos=6;blos<9;++blos){
					for(blol=0;blol<3;++blol){
                                                 if(thesudokusol[blos][blol]!=0){
							 num[thesudokusol[blos][blol]-1]=0;
						}
					}
				}
			}
			if(J>=3&&J<=5){
				for(blos=6;blos<9;++blos){
					for(blol=3;blol<6;++blol){
						if(thesudokusol[blos][blol]!=0){
							num[thesudokusol[blos][blol]-1]=0;
						}
					}
				}
			}
			if(J>=6&&J<=8){
				for(blos=6;blos<9;++blos){
					for(blol=6;blol<9;++blol){
						if(thesudokusol[blos][blol]!=0){
							num[thesudokusol[blos][blol]-1]=0;
						}
					}
				}
			}
		}
		int howmanynumber[9],l;
		for(i=0;i<9;++i){
			for(j=0;j<8;++j){
				if(thesudokusol[i][j]==0){
					for(k=0;k<9;++k)howmanynumber[k]=k+1;
					for(lin=0;lin<9;++lin){
						if(thesudokusol[i][lin]!=0){
							howmanynumber[thesudokusol[i][lin]-1]=0;
						}
					}
					for(str=0;str<9;++str){
						if(thesudokusol[str][j]!=0){
							howmanynumber[thesudokusol[str][j]-1]=0;
						}
					}
					if(i>=0&&i<=2){
						if(j>=0&&j<=2){
							for(blos=0;blos<3;++blos){
								for(blol=0;blol<3;++blol){
									if(thesudokusol[blos][blol]!=0){
										howmanynumber[thesudokusol[blos][blol]-1]=0;
									}
								}
							}
						}
						if(j>=3&&j<=5){
							for(blos=0;blos<3;++blos){
								for(blol=3;blol<6;++blol){
									if(thesudokusol[blos][blol]!=0){
										howmanynumber[thesudokusol[blos][blol]-1]=0;
									}
								}
							}
						}
						if(j>=6&&j<=8){
							for(blos=0;blos<3;++blos){
								for(blol=6;blol<9;++blol){
									if(thesudokusol[blos][blol]!=0){
										howmanynumber[thesudokusol[blos][blol]-1]=0;
									}
								}
							}
						}
					}
					if(i>=3&&i<=5){
						if(j>=0&&j<=2){
							for(blos=3;blos<6;++blos){
								for(blol=0;blol<3;++blol){
									if(thesudokusol[blos][blol]!=0){
										howmanynumber[thesudokusol[blos][blol]-1]=0;
									}
								}
							}
						}
						if(j>=3&&j<=5){
							for(blos=3;blos<6;++blos){
								for(blol=3;blol<6;++blol){
									if(thesudokusol[blos][blol]!=0){
										howmanynumber[thesudokusol[blos][blol]-1]=0;
									}
								}
							}
						}
						if(j>=6&&j<=8){
							for(blos=3;blos<6;++blos){
								for(blol=6;blol<9;++blol){
									if(thesudokusol[blos][blol]!=0){
										howmanynumber[thesudokusol[blos][blol]-1]=0;
									}
								}
							}
						}
					}
					if(i>=6&&i<=8){
						if(j>=0&&j<=2){
							for(blos=6;blos<9;++blos){
								for(blol=0;blol<3;++blol){
									if(thesudokusol[blos][blol]!=0){
										howmanynumber[thesudokusol[blos][blol]-1]=0;
									}
								}
							}
						}
						if(j>=3&&j<=5){
							for(blos=6;blos<9;++blos){
								for(blol=3;blol<6;++blol){
									if(thesudokusol[blos][blol]!=0){
										howmanynumber[thesudokusol[blos][blol]-1]=0;
									}
								}
							}
						}
						if(j>=6&&j<=8){
							for(blos=6;blos<9;++blos){
								for(blol=6;blol<9;++blol){
									if(thesudokusol[blos][blol]!=0){
										howmanynumber[thesudokusol[blos][blol]-1]=0;
									}
								}
							}
						}
					}
					l=0;
					for(k=0;k<9;++k){
						if(howmanynumber[k]!=0){
							 thesudokurest[i][j][l]=howmanynumber[k];
							 ++l;
						}
					}
				}
			}
		}
		solveway=0;
		for(i=0;i<9;++i){
			if(num[i]!=0){thebreak(num[i]);}
			if(solveway==2)break;
		}
		if(solveway==0)printf("0");
		if(solveway>=2)printf("2");
		if(solveway==1){
			printf("1\n");
			for(i=0;i<9;++i){
				for(j=0;j<9;++j){
					printf("%d%c",thetrueanswer[i][j],j==8?'\n':' ');
				}
			}
		}
	}
}
void Sudoku::changeNum(int a,int b)
{
if(a<1||a>9||b<1||b>9){return;}
int i,j;
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			if(thesudoku[i][j]==a){
				thesudoku[i][j]=b;
			}
			else if(thesudoku[i][j]==b){
				thesudoku[i][j]=a;
			}
		}
	}
}
void Sudoku::changeRow(int a,int b)
{
if(a<0||a>2||b<0||b>2){return;}
int i,j,A,B,comp;
A=3*a;
B=3*b;
	for(j=0;j<3;++j){
		for(i=0;i<9;++i){
			comp=thesudoku[A][i];
			thesudoku[A][i]=thesudoku[B][i];
			thesudoku[B][i]=comp;
		}
		A++;
		B++;
	}
}
void Sudoku::changeCol(int a,int b)
{
if(a<0||a>2||b<0||b>2){return;}
int i,j,cemp,A,B;
	A=3*a;
	B=3*b;
	for(j=0;j<3;++j){
        	for(i=0;i<9;++i){
                	cemp=thesudoku[i][A];
                	thesudoku[i][A]=thesudoku[i][B];
                	thesudoku[i][B]=cemp;
        	}
		A++;
		B++;
		
	}
}
void Sudoku::rotate(int n)
{
if(n<0||n>100){return;}
int new1[9][9],i,j,a,b;
if(n%4==0){
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			new1[i][j]=thesudoku[i][j];
		}
	}
        for(i=0;i<9;++i){
                for(j=0;j<9;++j){
                        thesudoku[i][j]=new1[i][j];
                }
        }
}
if(n%4==1){
	b=8;
	for(i=0;i<9;++i){
		a=0;
		for(j=0;j<9;++j){
			new1[a][b]=thesudoku[i][j];
			a++;
		}
		b=b-1;
	}
        for(i=0;i<9;++i){
                for(j=0;j<9;++j){
                        thesudoku[i][j]=new1[i][j];
                }
        }
}
if(n%4==2){
	a=8;
	for(i=0;i<9;++i){
		b=8;
		for(j=0;j<9;++j){
			new1[a][b]=thesudoku[i][j];
			b=b-1;
		}
		a=a-1;
	}
        for(i=0;i<9;++i){
                for(j=0;j<9;++j){
			thesudoku[i][j]=new1[i][j];
                }
        }
}
if(n%4==3){
	b=0;
        for(i=0;i<9;++i){
		a=8;
                for(j=0;j<9;++j){
			new1[a][b]=thesudoku[i][j];
			a=a-1;
                }
		b++;
        }
        for(i=0;i<9;++i){
                for(j=0;j<9;++j){
			thesudoku[i][j]=new1[i][j];
                }
        }
}
}
void Sudoku::flip(int n)
{
if(n<0||n>1){return;}
int new2[9][9],i,j;
if(n%2==0){
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			new2[8-i][j]=thesudoku[i][j];
		}
	}
        for(i=0;i<9;++i){
                for(j=0;j<9;++j){
			thesudoku[i][j]=new2[i][j];
                }
        }
}
if(n%2==1){
        for(j=0;j<9;++j){
                for(i=0;i<9;++i){
			new2[i][8-j]=thesudoku[i][j];
                }
        }
        for(i=0;i<9;++i){
                for(j=0;j<9;++j){
			thesudoku[i][j]=new2[i][j];
                }
        }

}
}
void Sudoku::transform()
{
	change();
	int i,j;
	printf("\n");
	for(i=0;i<9;++i){
		for(j=0;j<9;++j){
			printf("%d%c",thesudoku[i][j],j==8?'\n':' ');
		}
	}
}
void Sudoku::change(){
	srand(time(NULL));
	changeNum(rand()%9+1,rand()%9+1);
	changeRow(rand()%3,rand()%3);
	changeCol(rand()%3,rand()%3);
	rotate(rand()%101);
	flip(rand()%2);
}
